### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by HDVinnie** [laverix/mrmagnet#1]
Uncaught Error: [$injector:modulerr] Failed to instantiate module mrmagnet due to:
Error: [$injector:modulerr] Failed to instantiate module angular-svg-round-progress due to:
Error: [$injector:nomod] Module 'angular-svg-round-progress' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.6/$injector/nomod?p0=angular-svg-round-progress
    at file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:68:12
    at file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:2101:17
    at ensure (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:2025:38)
    at module (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:2099:14)
    at file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:4607:22
    at forEach (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:322:20)
    at loadModules (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:4591:5)
    at file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:4608:40
    at forEach (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:322:20)
    at loadModules (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:4591:5)
http://errors.angularjs.org/1.5.6/$injector/modulerr?p0=angular-svg-round-p…wnloads%2Fmrmagnet-master%2Fnode_modules%2Fangular%2Fangular.js%3A4591%3A5)
    at file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:68:12
    at file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:4630:15
    at forEach (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:322:20)
    at loadModules (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:4591:5)
    at file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:4608:40
    at forEach (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:322:20)
    at loadModules (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:4591:5)
    at createInjector (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:4513:19)
    at doBootstrap (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:1777:20)
    at bootstrap (file:///Users/Vinnie/Downloads/mrmagnet-master/node_modules/angular/angular.js:1798:12)
http://errors.angularjs.org/1.5.6/$injector/modulerr?p0=mrmagnet&p1=Error%3…nloads%2Fmrmagnet-master%2Fnode_modules%2Fangular%2Fangular.js%3A1798%3A12)

**Comment by owenvoke** [comment]
I get this too, think I know what's wrong. 👍
